### ISSUE TITLE
It would be nice to have the print statements commented out by-default , and enabled only for debugging 

### ISSUE THREAD

**Issue by shraddhabollapragada** [pvanallen/VarSpeedPython#1]
It would be nice to have the print statements in the sequence function of varspeed.py commented out by-default , and enabled only for debugging

**Comment by Jerzeek** [comment]
This issue is fixed with merge of pull request #5 !

**Comment by pvanallen** [comment]
Fully resolved now with Jerzeek's suggestion (thanks!). Now works with the debug parameter and modified the print statements to follow. All examples updated with 7bd01cd741a75369584b52fecbe155cdad467eac
